uhexen2: fix build
uhexen2 isn't C23 conform because it defines its own `true` and `false`
values (which have been declared keywords in the latest C standard).
This causes build failures with the newest versions of GCC unless one
tells the compiler to use an older standard:

```
In file included from ./quakeinc.h:29,
                 from ./quakedef.h:224,
                 from ../h2shared/gl_rlight.c:25:
../../common/q_stdinc.h:128:9: error: cannot use keyword 'false' as enumeration constant
  128 |         false = 0,
      |         ^~~~~
../../common/q_stdinc.h:128:9: note: 'false' is a keyword with '-std=c23' onwards
```